name: Deploy Frontend to Cloud Run

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE: book-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push
      run: |
        cd frontend
        docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/book-app-repo/frontend:$GITHUB_SHA .
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/book-app-repo/frontend:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/book-app-repo/frontend:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated