name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-south1
  SERVICE: book-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker
      run: gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Build and Push
      run: |
        cd backend
        docker build -t asia-south1-docker.pkg.dev/$PROJECT_ID/book-app-repo/backend:$GITHUB_SHA .
        docker push asia-south1-docker.pkg.dev/$PROJECT_ID/book-app-repo/backend:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE \
          --image asia-south1-docker.pkg.dev/$PROJECT_ID/book-app-repo/backend:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances ${{ secrets.DB_CONNECTION_NAME }} \
          --set-env-vars "DB_HOST=/cloudsql/${{ secrets.DB_CONNECTION_NAME }},DB_NAME=${{ secrets.DB_NAME }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},SPRING_DATASOURCE_URL=jdbc:postgresql:///bookdb?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${{ secrets.DB_CONNECTION_NAME }},SPRING_PROFILES_ACTIVE=prod"
          --timeout 900